# Global Configuration
source:         .
destination:    ./_site
baseurl:        "/blog"
encoding:       "utf-8"
timezone:       "America/Chicago"

# Build Commands
strict_front_matter:    true
#exclude: ["assets/js/MathJax"] # Enable in dev for faster builds
sass:
    style: compressed

plugins:
    - jekyll-feed

github_url: "https://github.com/C-Stevens/colinjstevens.com"
