# Global Configuration
source:         /home/web/www/cjs-stage/blog
destination:    /home/web/www/cjs-stage/blog/_site
baseurl:        "/blog"
encoding:       "utf-8"
timezone:       "America/Chicago"

# Build Commands
strict_front_matter:    true

plugins:
    - jekyll-feed

github_url: "https://github.com/C-Stevens/colinjstevens.com/"
